<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>congasharp</AssemblyName>
    <RootNamespace>CongaSharp</RootNamespace>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.*" />
    <PackageReference Include="K4os.Compression.LZ4" Version="1.*" />
    <PackageReference Include="ZstdSharp.Port" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CongaSharp.Tests" />
  </ItemGroup>

</Project>
